<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <!-- You can use net9.0 if that’s your standard -->
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
	<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
	<LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
