name: Build, Package and Publish NuGet

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  DOTNET_VERSION: '8.X'
  BUILD_CONFIGURATION: 'Release'

#permissions:
# contents: read
#  packages: write

jobs:

  security-scan:
    name: Security Scan (GitLeaks)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

  lint:
    name: Lint and Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
